apiVersion: v1
kind: ConfigMap
metadata:
  name: acctadmin-cm
#  namespace: {{ .Values.namespace }}
data:
{{- $root := . }}
{{- range $path, $byte := .Files.Glob "app_configs/*" }}
{{ base $path | indent 2}}: |
{{ tpl ($root.Files.Get $path) $root | indent 4}}
{{- end}}