apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.mssvcname }}"
#  namespace: "{{ .Values.kube_namespace }}"
  labels:
    app: "{{ .Values.msname }}"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ .Values.msname }}"